### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by blksnk** [blksnk/yunglabz-vue#1]
# LOGIC & ANIMATION

- [ ] initial loader
- [ ] content page transition
- [ ] audio functions
- [ ] js bezier function

# CONTENT

- [ ] presentation page
- [ ] artist page
- [ ] create and link to api

# GL

- [ ] audio play animations
- [ ] transition on url change
- [ ] presentation scene
- [ ] artist scene
- [ ] finish optimizing 3d models
- [x] reduce texture resolution
- [ ] screen reflection / glare map
- [x] screen lightup light -> THREE.RectAreaLight

# MOBILE

- [ ] mobile ui
- [ ] center to scene when mobile 
- [ ] touch event -> deactivate mouse event functions
- [ ] features activation based on device perf
- [ ] post processing
